### ISSUE TITLE
npm install previous version ?

### ISSUE THREAD

**Issue by frolov32** [pdlove/homebridge-sensibo#12]
Hi @pdlove @payote  @leoneleone 
It seems to me that the command
`npm install -g homebridge-sensibo` 
installs the previous version. 
If i try to install it manually i get some errors. Faced with this after reinstalling the system.
Any chance a revival of the plugin or any improvements?

**Comment by leoneleone** [comment]
I've just changed a few things so the plugin will now work under iOS 9.3.2 HomeKit, submitted a pull request.

I suggest using a different install method, by using the direct url address of the github (homebridge-sensibo) page:
npm install -g git+https...

just waiting on @pdlove to OK the pull request

**Comment by frolov32** [comment]
Thank you @leoneleone !
NPM install -G git+https... - work great!
I have some strange problem. On/off switch constantly on.) 
after i press "off" button he can turn off my air condition but then immediately change status to "on" again. air conditioning off. 
so I can't turn on the air conditioner with a switch but only by changing the target temperature.

**Comment by pdlove** [comment]
I've updated npm with the latest version. I'll try to remember to do that any time we commit.
