### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pbassham** [pdlove/homebridge-sensibo#8]
/usr/local/lib/node_modules/homebridge-sensibo/accessories/pods.js:133
        .Characteristic(Characteristic.CurrentRelativeHumidity)

i had to add ".getCharacteristic"

**Comment by leoneleone** [comment]
yes you are right. sorry for the long delay.
I've submitted a pull request that fixes that issue and a couple of others (Characteristic.On, and Characteristic.RotationSpeed)
