### ISSUE TITLE
Accessories not showing up in HomeKit app

### ISSUE THREAD

**Issue by pbassham** [pdlove/homebridge-sensibo#9]
I got everything configured and it is asking me to scan the code with my HomeKit app, but it is not showing in the HomeKit app like it did before. 

I recently deleted the HomeKit profile, updated homebridge and this plugin, and relaunched to start over, but it's not working now. 

Any ideas?

**Comment by pdlove** [comment]
You'll need to also delete the persist folder which should be in the same folder as your config.json.

**Comment by pbassham** [comment]
Thanks. That works.
